### ISSUE TITLE
Object On Object

### ISSUE THREAD

**Issue by ghost** [petersirka/jquery.templates#1]
How i do access object on object using jquery.templates ?

**Comment by petersirka** [comment]
Hi @soejin,
please use my another template engine https://github.com/totaljs/Tangular.

Thank you.

**Comment by petersirka** [comment]
PS: this is not possible what you want.

**Comment by ghost** [comment]
But i have the project on his, no have any outher things ?
`
//Begin Code
var person = {
              id  : 1 ,
              firstName : "Douglas" , 
              lastName : "Dreer" ,
              email : "douglasdreer@email.com" ,
              photos : [
               { file : "photo_1.jpg" , title : "Photo 1" } ,
               { file : "photo_2.jpg" , title : "Photo 2" }
              ]
};

$(".content-body").template(person);

//End Code
`
`

<div class="table-responsive">
            <table class="table table-hover">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Photos</th>
                  </tr>
                </thead>
                <tbody>
                    <tr class="content-body">
                        <td>{id}</td>
                        <td>{firstName}</td>
                        <td>{lastName}</td>
                        <td><img src="{photo.file}" alt="{photo.rotule}" title="photo.title" /></td>
                    </tr>
                </tbody>
            </table>
`

**Comment by petersirka** [comment]
Looping doesn't work in this template engine ... Do you want to iterate photos?

**Comment by ghost** [comment]
Yes I need.
I'm doing a report with information soil, topography and information about the building, such as the front of the photo, condition etc ...

For I decided to use the template and add the variables to fill the data.

**Comment by petersirka** [comment]
I'm so sorry, as I wrote ––> use `Tangular`. With this template engine is not possible what you want.

**Comment by ghost** [comment]
Thanks for the help, but I could make an adjustment so that you can solve my little problem. In my country (Brazil) this "small" setting is called "**Gambiarra**" I do not know the English equivalent. = D

As soon as possible I will take a look at TAngular.

follows the code below:

Thanks again for your attention.

`
//Begin Code
var person = {
id : 1 ,
firstName : "Douglas" , 
lastName : "Dreer" ,
email : "douglasdreer@email.com" ,
photos : "<img src='path_to_file' alt='alt_to_file' title='title_to_file' />" +
              "<img src='path_to_file' alt='alt_to_file' title='title_to_file' />"
};
`

`

<div class="table-responsive">
            <table class="table table-hover">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Photos</th>
                  </tr>
                </thead>
                <tbody>
                    <tr class="content-body">
                        <td>{id}</td>
                        <td>{firstName}</td>
                        <td>{lastName}</td>
                        <td>{!photos}</td>
                    </tr>
                </tbody>
            </table>
        </div>

`

Thanks again for your attention.
